image:
  repository: fogshaper/cassiopeia-backend
  tag: v4

replicaCount: 1

service:
  port: 8080

postgres:
  image: postgres:16-alpine
  user: cassiopeia
  password: cassiopeia
  database: cassiopeia
  storage: 1Gi
