{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cassiopeia-backend-db
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cassiopeia-backend-db
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: user
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: password
    - secretKey: database
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: database
{{- end }}
