apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassiopeia-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cassiopeia-frontend
  template:
    metadata:
      labels:
        app: cassiopeia-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cassiopeia-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cassiopeia-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cassiopeia-frontend
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.route.gatewayName }}
  hostnames:
    - {{ .Values.route.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: cassiopeia-frontend
          port: {{ .Values.service.port }}
